module.exports = function (turndownService) {
    // Footnote Reference: [1] -> [^id]
    turndownService.addRule('footnote-ref', {
        filter: (node) => {
            // Check if it's an anchor with href starting with #
            if (node.nodeName === 'A' && node.getAttribute('href') && node.getAttribute('href').startsWith('#')) {
                // Check if text content looks like [1] or 1
                const text = node.textContent.trim();
                return /^\[?\d+\]?$/.test(text);
            }
            return false;
        },
        replacement: (content, node) => {
            const href = node.getAttribute('href');
            const id = href.substring(1); // Remove #
            return `[^${id}]`;
        }
    });

    // Footnote Definition: content with ID -> [^id]: content
    turndownService.addRule('footnote-def', {
        filter: (node) => {
            const tags = ['p', 'div', 'li', 'aside'];
            if (!tags.includes(node.nodeName.toLowerCase())) return false;
            if (!node.hasAttribute('id')) return false;

            const text = node.textContent.trim();
            // Match [1] ... or 1. ... or 1 ...
            // Also check if ID is referenced? (Hard without state)
            // Heuristic: Content must start with [d] or d. AND have ID.
            return /^\[?\d+\]?/.test(text) && (node.getAttribute('epub:type') === 'footnote' || text.length < 500);
        },
        replacement: (content, node) => {
            const id = node.getAttribute('id');
            // Clean content: remove [1] or \[1\] or 1. at start
            // Turndown escapes [ to \[.
            let cleanContent = content.replace(/^(\\?\[)?\d+(\\?\])?\.?\s*/, '');

            // Remove Obsidian-style internal back-links generated by internal-links rule
            // Supports both old Block ID format: [[#^ref1|^]] and new heading-text format: [[#Heading|↩]]
            cleanContent = cleanContent.replace(/\s*\[\[#[^\]]+\|(\^|↩|back)\]\]\s*$/i, '');

            return `[^${id}]: ${cleanContent}`;
        }
    });
};
